name: Publish to PyPI

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Optional, environment configuration (step 5)

    permissions:
      id-token: write
      contents: read  # Grant minimal permissions needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
